### ISSUE TITLE
get_xxxx_schema() methods should return schemas

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/my-lab-to-nwb-template#3]
Since DataInterfaces should interface specific data types with NWB structure, I believe they should also return complete schemas, header and all (not only a dictionary that would fit inside the schema['properties']). I think this should apply to both `input_schema` and `metadata_schema`.

### Why?

I think this standardization would cost close to nothing and only helps understanding each piece of the project. If you call `get_xxxx_schema()` you should get a schema, not only the potential contents for one.

### What that requires?

It requires minor changes in `get_input_schema()` and `get_metadata_schema()`, to start them of with the schema header and the fill the properties accordingly.

### input_schema

We've been [discussing](https://github.com/catalystneuro/nwb-conversion-tools/pull/66) whether `input_schema` should carry the keywords `source_data` and `conversion_options` or not. We have flattened them to input_args properties of DataInterfaces so older Converters won't break immediately, but I honestly don't think this is a good enough argument to not make the change, which should be quite simple to do.

Because I do feel like these are different properties of a conversion task, I slightly favor keeping these properties keywords in the `input_schema`. As a plus, the `input_schema` could be automatically treated as any other schema in the Dash-Forms, getting the nice visual distinction of forms out of the box, without the need of special treatment.

I know by now that I'm outvoted on this, so I have no problem in adopting a flat properties in `input_schema`. Just wanted to leave the discussion here for reference.

**Comment by bendichter** [comment]
what about using source_data for `__init__` args and `conversion_options` for `run_conversion` args

**Comment by bendichter** [comment]
@CodyCBakerPhD Luiz and I are discussing this now. We think that `DataInterface.get_input_schema` should return a full json-schema dict with properties `source_data` and `conversion_options`, where `source_data` is routed to `DataInterface.__init__` and `conversion_options` is routed to `DataInterface.run_conversion`. What do you think about that?

**Comment by CodyCBakerPhD** [comment]
A full json schema sounds perfectly fine, that's definitely a good idea; and to be fair, most of the changes wouldn't be necessary at the `get_input_schema` level but rather the helper functions they rely on like `get_schema_from_method_signature`.

In general it seems OK on the routing, but where exactly does this routing occur? With the current setup it seems like it would be easier to have a separate function `DataInterface.get_conversion_options` to call in the general `Converter.run_conversion`, exactly like how the `get_input_schema` works in `init` right now.

**Comment by bendichter** [comment]
I think `DataInterface.get_conversion_options` would simply be `utils.get_schema_from_method_signature(DataInterface.run_conversion)`

**Comment by CodyCBakerPhD** [comment]
This has been implemented since then.
