### ISSUE TITLE
How to combine DataInterfaces metadata?

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/my-lab-to-nwb-template#5]
Any two DataInterfaces could potentially fetch the values for the same metadata fields, most notably NWBFile (but also others, such as Subject). How should we deal with this?

### 1. Extra optional arguments for DataInterface.get_metadata()

The method `get_metadata()` of DataInterfaces could have **optional** args `metadata` and `overwrite`, which would provide it with any partially filled metadata and the instruction whether to overwrite any pre-existing fields or pass them.
The Converter would choose the sequence of DataInterfaces and the combination of the passed `overwrite` args.

### 2. Converter gets pure DataInterface metadata

DataInterfaces will always return the same metadata and Converter will figure out how to combine them.

**Comment by bendichter** [comment]
I'd vote for option 2, where the DataInterface naively passes all of the metadata it can to the Converter and the Converter decides on precedence. One caveat might be if for some reason `get_metadata` is expensive and this value would just be overwritten, then maybe we could specify which values to extract.

**Comment by CodyCBakerPhD** [comment]
Old issue long resolved by `deep_dict_update`
