### ISSUE TITLE
[ToDo] Setup cache with GIN data

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/my-lab-to-nwb-template#8]
It would be nice to setup this repo to have a scheduled (say, once a week) small-scale test using GIN data just to ensure the default templates for ecephys/ophys/icephys work OK.

**Comment by CodyCBakerPhD** [comment]
Also setup badges in README for frontal display of scheduled install+GIN workflows.

**Comment by bendichter** [comment]
wouldn't this be covered by NCT tests?

**Comment by CodyCBakerPhD** [comment]
> wouldn't this be covered by NCT tests?

The actual functionality of the conversion, yes, but I just mean specific to the usage on this repo to ensure we're not copying/pasting a bad template (or that changes upstream break the template)

**Comment by bendichter** [comment]
I worry about running automated tests regularly for lab-specific repos. Do you think this might scale poorly and use up all of our free cloud hours?

**Comment by CodyCBakerPhD** [comment]
I wasn't proposing for all downstream repos, just for the template one. Such tests could sit on a secondary branch and still trigger on a schedule so they don't get copied over.

Also, I haven't heard of any finite limit on 'free cloud hours' for open source projects. Not that we should push it, but just doing a small subset of what we have on NWBCT shouldn't add up to that much either.

Also also, that's why I'm suggesting a weekly schedule not an on-push sort of trigger, which would result in total running hours on a far lower order of magnitude than on NWBCT.

**Comment by bendichter** [comment]
We have 2,000 free minutes / month [source](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions
)

I guess I'm not understanding what would be tested here that we aren't already testing in NCT. I would rather push classes upsteam to NCT if they are shared across several conversion repos, and if the classes are defined in NCT then the tests should be defined there as well. Can you give me an example of what these automated tests would cover?

**Comment by CodyCBakerPhD** [comment]
> We have 2,000 free minutes / month [source](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions)

That refers to private repositories under the 'free' plan. For public repos: "GitHub Actions usage is free for both public repositories and self-hosted runners."

Also note that this must be true since a single push on NWBCT uses an average of 15 action minutes per platform/pyVersion, of which we cover 9 combinations, so 10 pushes on two PRs over the course of a single day would more than use up our monthly allotment within a single day.

**Comment by CodyCBakerPhD** [comment]
> Can you give me an example of what these automated tests would cover?

Point of these tests is not to ensure the `run_conversion` of individual interfaces works, but if the script `convert_my_data.py` runs successfully, and continue to run successfully over time using loose version dependency on all upstream dependency (CT full tests only use strict dependency for consistency atm).
